services:
  # INFRASTRUCTURE

  db-product:
    image: mongo
    container_name: db-product
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: product-service
    ports:
      - "27017:27017"
    volumes:
      - ./product-service/data:/data/db

  db-order:
    image: mysql:9.5.0
    container_name: db-order
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: order-service
    volumes:
      - ./order-service/data:/data/db

  db-inventory:
    image: mysql:9.5.0
    container_name: db-inventory
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: inventory-service
    volumes:
      - ./inventory-service/data:/data/db

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  eureka-server:
    image: rnk7/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    image: rnk7/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  # SERVICES

  inventory-service:
    image: rnk7/inventory-service:latest
    container_name: inventory-service
    ports:
      - "8081:8081"
    depends_on:
      - db-inventory
      - eureka-server
      - api-gateway

  notification-service:
    image: rnk7/notification-service:latest
    container_name: notification-service
    ports:
      - "8084:8084"
    depends_on:
      - broker

  order-service:
    image: rnk7/order-service:latest
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - db-order
      - broker
      - api-gateway
      - eureka-server
      - inventory-service

  product-service:
    image: rnk7/product-service:latest
    container_name: product-service
    ports:
      - "8083:8083"
    depends_on:
      - db-product
      - eureka-server
      - api-gateway



