version: '4'
services:
  mysql:
    image: mysql:9.5.0
    container_name: inventory-service-mysql
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: inventory-service
    volumes:
      - ./data:/data/db